### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by hukendo** [abiosoft/dockward#2]
Release 0.0.2 compile with the error. You can release a new version from the master branch? Need it for homebrew formula.

**Comment by abiosoft** [comment]
I don't quite understand the issue.

Are you trying to build from source and getting compile time error or you want me to do a new release ?

**Comment by hukendo** [comment]
I want you do make a new release, pls.

**Comment by abiosoft** [comment]
Yeah, that's it. https://github.com/abiosoft/dockward/releases/tag/0.0.3.

May I know what error you are getting with 0.0.2 ?

**Comment by hukendo** [comment]
thx
error:

```
src/github.com/abiosoft/dockward/network/network.go:27: not enough arguments in call to client.NetworkCreate
src/github.com/abiosoft/dockward/network/network.go:40: not enough arguments in call to n.client.NetworkConnect
src/github.com/abiosoft/dockward/network/network.go:45: not enough arguments in call to n.client.NetworkDisconnect
src/github.com/abiosoft/dockward/network/network.go:51: not enough arguments in call to n.client.NetworkInspect
src/github.com/abiosoft/dockward/network/network.go:57: not enough arguments in call to n.client.NetworkDisconnect
src/github.com/abiosoft/dockward/network/network.go:62: not enough arguments in call to n.client.NetworkRemove
```

**Comment by abiosoft** [comment]
Oh you're building from source. That's a dependency issue I've resoved. `go get -u github.com/abiosoft/dockward` should fix it.

**Comment by abiosoft** [comment]
@hukendo did you end up doing the homebrew formula ?

**Comment by abiosoft** [comment]
@hukendo found it. Do you mind updating the brew formula to version 0.0.4.

Thanks.
